# ReconScan System Configuration
# Static settings for system-level configuration and defaults
# These settings are typically set once and rarely changed during runtime

# Application information
app:
  name: "ReconScan"
  version: "0.3.01-dev"
  build: "alpha"
  author: "Seichs"
  description: "AI-Enhanced Web Application Vulnerability Scanner"

# System requirements and compatibility
system:
  min_python_version: "3.8"
  max_memory_usage: "2GB"
  max_concurrent_scans: 5
  default_encoding: "utf-8"
  temp_dir: "temp"

# File paths and directories
paths:
  payloads_dir: "config/payloads"
  wordlists_dir: "data/wordlists"
  reports_dir: "reports"
  logs_dir: "logs"
  temp_dir: "temp"
  custom_modules_dir: "scanner/custom"

# Module configuration and defaults
modules:
  # Modules enabled by default
  enabled_by_default:
    - "sql_injection"
    - "xss"
    - "lfi"
    - "command_injection"
    - "headers"
  
  # Modules disabled by default (experimental or high-risk)
  disabled_by_default:
    - "experimental_module"
    - "destructive_tests"
  
  # Auto-load custom modules from custom_modules_dir
  auto_load_custom: true
  
  # Module loading timeout (seconds)
  load_timeout: 30

# Default payload configurations
payload_defaults:
  sql_injection:
    default_level: "advanced"          # basic, medium, advanced - USE ADVANCED FOR BETTER DETECTION
    time_based_delay: 3                # Reduced from 5 to 3 seconds for faster scanning
    error_based_enabled: true
    blind_enabled: true
    union_enabled: true
    false_positive_filtering: false    # DISABLE AI filtering for more thorough detection
    max_payloads_per_param: 100        # Increased payload limit for comprehensive testing
  
  xss:
    default_encoding: "all"            # Changed from standard to all for better coverage
    dom_testing: true
    stored_testing: true
    reflected_testing: true
    false_positive_filtering: false    # DISABLE AI filtering for more thorough detection
    max_payloads_per_param: 75         # Increased payload limit
  
  command_injection:
    default_os: "both"                 # Changed from auto to both for better coverage
    time_based_delay: 2                # Reduced delay for faster scanning
    blind_enabled: true
    max_payloads_per_param: 50
  
  lfi:
    directory_traversal: true
    wrapper_testing: true
    filter_bypass: true
    max_payloads_per_param: 60

# Integration settings for external tools
integrations:
  burp_suite:
    enabled: false
    api_url: "http://127.0.0.1:1337"
    api_key: null
  
  metasploit:
    enabled: false
    rpc_host: "127.0.0.1"
    rpc_port: 55553
  
  custom_tools:
    enabled: false
    tools_path: "/opt/security-tools"

# Default network and scanning behavior - OPTIMIZED FOR BETTER PERFORMANCE
defaults:
  network:
    proxy: null
    timeout: 30                        # INCREASED from 10 to 30 seconds to prevent timeouts
    user_agent: "ReconScan/1.0"
    max_redirects: 5
    verify_ssl: false
    retry_attempts: 2                  # Reduced from 3 to 2 for faster scanning
    connection_pool_size: 100          # Added connection pooling
  
  scanning:
    threads: 3                         # REDUCED from 5 to 3 to prevent rate limiting
    delay: 1.0                         # INCREASED from 0.5 to 1.0 second delay to be more polite
    deep_scan: true                    # ENABLED deep scanning for better coverage
    follow_redirects: true
    scan_timeout: 600                  # INCREASED from 300 to 600 seconds (10 minutes)
    max_urls: 2000                     # INCREASED from 1000 to 2000 for better coverage
    max_crawl_urls: 50                 # INCREASED crawling limit
    max_discovered_urls: 100           # INCREASED discovery limit
    max_urls_for_testing: 100          # INCREASED testing limit
  
  output:
    verbose: true
    save_responses: false
    report_format: "json"
    log_level: "INFO"
    color_output: true

# Wordlist and dictionary settings
wordlists:
  default_dirs: "common_directories.txt"
  default_files: "common_files.txt"
  default_params: "common_parameters.txt"
  custom_wordlists_enabled: true

# Security and safety settings
security:
  max_payload_size: "10MB"
  dangerous_functions_check: true
  safe_mode: false
  whitelist_enabled: false
  blacklist_enabled: true
